---
name: Windows Smoke

'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  windows:
    env:
      BUNDLE_without: integration
      machine_user: test_user
      machine_pass: Pass@word1
      machine_port: 5985
      SPEC_OPTS: --format progress
    runs-on: windows-2019
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1']
        yaml: ['windows.yml', 'windows-product.yml']
    name: Windows Smoke test on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake unit && bundle exec rake quality
      - run: |
          winrm.cmd quickconfig -q
          net user /add %machine_user% %machine_pass%
          net localgroup administrators %machine_user% /add
          bundle install --with integration
          bundle exec kitchen verify windows
        env:
          KITCHEN_YAML: ${{ matrix.yaml}}
