---
name: Unit

'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    env:
      BUNDLE_WITHOUT: integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0', '3.1']
    name: Unit test on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake unit features
  coverage-report:
    needs: test
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Coverage Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: 90
          resultPath: coverage/.last_run.json
